(cl:in-package freyja_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          BEST_LAT-VAL
          BEST_LAT
          BEST_LON-VAL
          BEST_LON
          HGT-VAL
          HGT
          SP_X-VAL
          SP_X
          SP_Y-VAL
          SP_Y
          BEST_SP_X-VAL
          BEST_SP_X
          BEST_SP_Y-VAL
          BEST_SP_Y
          BEST_SP_Z-VAL
          BEST_SP_Z
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          PITCH_ANGLE-VAL
          PITCH_ANGLE
          ROLL_ANGLE-VAL
          ROLL_ANGLE
          YAW_ANGLE-VAL
          YAW_ANGLE
          PITCH_ANGLEVEL-VAL
          PITCH_ANGLEVEL
          ROLL_ANGLEVEL-VAL
          ROLL_ANGLEVEL
          YAW_ANGLEVEL-VAL
          YAW_ANGLEVEL
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          MOTOR1RPM-VAL
          MOTOR1RPM
          MOTOR2RPM-VAL
          MOTOR2RPM
          MOTOR3RPM-VAL
          MOTOR3RPM
          MOTOR4RPM-VAL
          MOTOR4RPM
          MOTOR5RPM-VAL
          MOTOR5RPM
          MOTOR6RPM-VAL
          MOTOR6RPM
))