// Generated by gencpp from file freyja_msgs/CurrentState.msg
// DO NOT EDIT!


#ifndef FREYJA_MSGS_MESSAGE_CURRENTSTATE_H
#define FREYJA_MSGS_MESSAGE_CURRENTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace freyja_msgs
{
template <class ContainerAllocator>
struct CurrentState_
{
  typedef CurrentState_<ContainerAllocator> Type;

  CurrentState_()
    : header()
    , state_vector()
    , state_valid(0)  {
      state_vector.assign(0.0);
  }
  CurrentState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state_vector()
    , state_valid(0)  {
  (void)_alloc;
      state_vector.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 13>  _state_vector_type;
  _state_vector_type state_vector;

   typedef uint8_t _state_valid_type;
  _state_valid_type state_valid;





  typedef boost::shared_ptr< ::freyja_msgs::CurrentState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freyja_msgs::CurrentState_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentState_

typedef ::freyja_msgs::CurrentState_<std::allocator<void> > CurrentState;

typedef boost::shared_ptr< ::freyja_msgs::CurrentState > CurrentStatePtr;
typedef boost::shared_ptr< ::freyja_msgs::CurrentState const> CurrentStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freyja_msgs::CurrentState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freyja_msgs::CurrentState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::freyja_msgs::CurrentState_<ContainerAllocator1> & lhs, const ::freyja_msgs::CurrentState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state_vector == rhs.state_vector &&
    lhs.state_valid == rhs.state_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::freyja_msgs::CurrentState_<ContainerAllocator1> & lhs, const ::freyja_msgs::CurrentState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace freyja_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::freyja_msgs::CurrentState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freyja_msgs::CurrentState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freyja_msgs::CurrentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freyja_msgs::CurrentState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freyja_msgs::CurrentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freyja_msgs::CurrentState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freyja_msgs::CurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb3e9083594b5a85032db45485cf4a00";
  }

  static const char* value(const ::freyja_msgs::CurrentState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb3e9083594b5a85ULL;
  static const uint64_t static_value2 = 0x032db45485cf4a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::freyja_msgs::CurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freyja_msgs/CurrentState";
  }

  static const char* value(const ::freyja_msgs::CurrentState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freyja_msgs::CurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Full state generated for the controller:\n"
"# [pn, pe, pd, vn, ve, vd, roll, pitch, yaw, rrate, prate, yrate, delta_t]\n"
"Header header\n"
"float64[13] state_vector\n"
"uint8       state_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::freyja_msgs::CurrentState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freyja_msgs::CurrentState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state_vector);
      stream.next(m.state_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freyja_msgs::CurrentState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::freyja_msgs::CurrentState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state_vector[]" << std::endl;
    for (size_t i = 0; i < v.state_vector.size(); ++i)
    {
      s << indent << "  state_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state_vector[i]);
    }
    s << indent << "state_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREYJA_MSGS_MESSAGE_CURRENTSTATE_H
