// Generated by gencpp from file freyja_msgs/CurrentStateBiasEst.msg
// DO NOT EDIT!


#ifndef FREYJA_MSGS_MESSAGE_CURRENTSTATEBIASEST_H
#define FREYJA_MSGS_MESSAGE_CURRENTSTATEBIASEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace freyja_msgs
{
template <class ContainerAllocator>
struct CurrentStateBiasEst_
{
  typedef CurrentStateBiasEst_<ContainerAllocator> Type;

  CurrentStateBiasEst_()
    : header()
    , state_vector()  {
      state_vector.assign(0.0);
  }
  CurrentStateBiasEst_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state_vector()  {
  (void)_alloc;
      state_vector.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 12>  _state_vector_type;
  _state_vector_type state_vector;





  typedef boost::shared_ptr< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentStateBiasEst_

typedef ::freyja_msgs::CurrentStateBiasEst_<std::allocator<void> > CurrentStateBiasEst;

typedef boost::shared_ptr< ::freyja_msgs::CurrentStateBiasEst > CurrentStateBiasEstPtr;
typedef boost::shared_ptr< ::freyja_msgs::CurrentStateBiasEst const> CurrentStateBiasEstConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator1> & lhs, const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state_vector == rhs.state_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator1> & lhs, const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace freyja_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ab5d62c27ac2f41f121e92a2fdaa3ca";
  }

  static const char* value(const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ab5d62c27ac2f41ULL;
  static const uint64_t static_value2 = 0xf121e92a2fdaa3caULL;
};

template<class ContainerAllocator>
struct DataType< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
{
  static const char* value()
  {
    return "freyja_msgs/CurrentStateBiasEst";
  }

  static const char* value(const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Estimated state augmented with bias estimates\n"
"# [pn, pe, pd, vn, ve, vd, bn, be, bd, debug1, debug2, debug3]\n"
"# Use debug to monitor the variance of estimator, for instance.\n"
"Header header\n"
"float64[12] state_vector\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentStateBiasEst_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::freyja_msgs::CurrentStateBiasEst_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state_vector[]" << std::endl;
    for (size_t i = 0; i < v.state_vector.size(); ++i)
    {
      s << indent << "  state_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREYJA_MSGS_MESSAGE_CURRENTSTATEBIASEST_H
