# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from freyja_msgs/AsctecCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AsctecCommand(genpy.Message):
  _md5sum = "56ac1fe81e2a3c53f5aeb626327e1b63"
  _type = "freyja_msgs/AsctecCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# asctec handler common message structure that contains everything commandable
## command_type =   1   :   this message is to turn motors on or off
##                  2   :   this message is to idle the motors
##                  3   :   this message is to command attitudes

uint8 command_type
float64 roll
float64 pitch
float64 yaw
float64 thrust
uint8 ctrl_byte
"""
  __slots__ = ['command_type','roll','pitch','yaw','thrust','ctrl_byte']
  _slot_types = ['uint8','float64','float64','float64','float64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command_type,roll,pitch,yaw,thrust,ctrl_byte

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AsctecCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command_type is None:
        self.command_type = 0
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.thrust is None:
        self.thrust = 0.
      if self.ctrl_byte is None:
        self.ctrl_byte = 0
    else:
      self.command_type = 0
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.thrust = 0.
      self.ctrl_byte = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4dB().pack(_x.command_type, _x.roll, _x.pitch, _x.yaw, _x.thrust, _x.ctrl_byte))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.command_type, _x.roll, _x.pitch, _x.yaw, _x.thrust, _x.ctrl_byte,) = _get_struct_B4dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4dB().pack(_x.command_type, _x.roll, _x.pitch, _x.yaw, _x.thrust, _x.ctrl_byte))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.command_type, _x.roll, _x.pitch, _x.yaw, _x.thrust, _x.ctrl_byte,) = _get_struct_B4dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4dB = None
def _get_struct_B4dB():
    global _struct_B4dB
    if _struct_B4dB is None:
        _struct_B4dB = struct.Struct("<B4dB")
    return _struct_B4dB
